language: csharp
solution: SMASH.sln
install:
  - nuget restore SMASH.sln
  - nuget install NUnit.Runners -Version 3.2.1 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release SMASH.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.2.1/tools/nunit3-console.exe ./SMASH.Tests/bin/Release/SMASH.Tests.dll
