language: objective-c
osx_image: xcode7.3

script:
  - xcodebuild -workspace SMASH.xcworkspace -scheme SMASH ONLY_ACTIVE_ARCH=NO
  - xcodebuild -workspace SMASH.xcworkspace -scheme SMASH -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6s,OS=9.3' test