node {
        stage 'Checkout'
            checkout scm	

        stage 'Pre-Build'
            sh 'pod install'

        stage 'Build'
            sh 'xcodebuild -workspace "SMASH.xcworkspace" -scheme "SMASH"  ONLY_ACTIVE_ARCH=NO' 
                stage 'Test'
            sh 'xcodebuild -workspace "SMASH.xcworkspace" -scheme "SMASH" -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 6s,OS=9.3" test'
        }